# Settings for the Puya P25Q32SH 4MiB SPI flash.
# Datasheet: https://www.puyasemi.com/uploadfiles/2021/08/202108231550495049.pdf
total_size = 0x400000 # 4 MiB # Page 19
capacity = 0x16 # page 80
write_status_register_split = true # page 36
01_continuous_status_write = true # page 25
e7_quad_word_read = true # page 24
