manufacturer_id = 0xc8
memory_type = 0x40
quad_enable_bit_mask = 0x02
has_sector_protection = false
quad_enable_status_byte = 2
6b_quad_read = true
32_qspi_write = true
use_global_block_protection_lock = false
