# Settings for the Microchip SST26VF016B 16Mb (2MiB) QSPI flash.
# Datasheet: https://www.microchip.com/en-us/product/SST26VF016B
total_size = 0x200000 # 2 MiB
memory_type = 0x26
capacity = 0x41
start_up_time_us = 10000
max_clock_speed_mhz = 104
single_status_byte = true
write_status_register_split = false
quad_enable_bit_mask = 0x00
quad_enable_status_byte = 1
6b_quad_read = true
32_qspi_write = true
